[tool.poetry]
name = "aerich"
version = "0.1.9"
description = "A database migrations tool for Tortoise ORM."
authors = ["long2ice <long2ice@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/long2ice/aerich"
repository = "git@github.com:long2ice/aerich.git"
documentation = "https://github.com/long2ice/aerich"
keywords = ["migrate", "Tortoise-ORM", "mysql"]
packages = [
    { include = "aerich" }
]
include = ["CHANGELOG.rst", "LICENSE", "README.rst"]

[tool.poetry.dependencies]
python = "^3.8"
tortoise-orm = "*"
asyncclick = "*"
pydantic = "*"

[tool.poetry.dev-dependencies]
taskipy = "*"
flake8 = "*"
isort = "*"
black = "^19.10b0"
pytest = "*"
pytest-xdist = "*"
mypy = "*"
pytest-asyncio = "*"

[tool.poetry.extras]
dbdrivers = ["aiomysql", "asyncpg"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
aerich = "aerich.cli:main"