[tool.poetry]
name = "aerich"
version = "0.1.7"
description = "A database migrations tool for Tortoise ORM."
authors = ["long2ice <long2ice@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tortoise-orm = {git = "https://github.com/tortoise-orm/tortoise-orm.git", branch = "develop"}
asyncclick = "*"
pydantic = "*"

[tool.poetry.dev-dependencies]
taskipy = "*"
asynctest = "*"
flake8 = "*"
isort = "*"
black = "^19.10b0"
pytest = "*"
aiomysql = "*"
asyncpg = "*"
pytest-xdist = "*"
mypy = "*"

[tool.taskipy.tasks]
export = "poetry export -f requirements.txt --without-hashes > requirements.txt"
export-dev = "poetry export -f requirements.txt --dev --without-hashes > requirements-dev.txt"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

