name: pypi
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          args: install
      - name: Build dists
        run: |
          make build
      - name: Pypi Publish
        run: |
          make publish