name: test
on: [push, pull_request]
jobs:
  testall:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: 123456
          POSTGRES_USER: postgres
        options: --health-cmd=pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - uses: actions/checkout@v2
      - name: Install poetry
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          args: install
      - name: CI
        env:
          MYSQL_PASS: root
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          POSTGRES_PASS: 123456
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
        run: make testall